name: "news-feed"

networks:
  news-feed-network:

services:
  api:
    build:
      context: api
      dockerfile: ./Dockerfile
    restart: always
    environment:
      GIN_MODE: release
    ports:
      - "2912:2912"
    networks:
      - news-feed-network

  web:
    build:
      context: news-app
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - news-feed-network
