[general]

host = "0.0.0.0"
port = 2912
root = "./dist/news-app/browser"

log-level = "info"

http2 = true
http2-tls-cert = "auth/certificate.crt"
http2-tls-key = "auth/key.key"
https-redirect = false
https-redirect-host = "localhost"
https-redirect-from-port = 80
https-redirect-from-hosts = "localhost"
